### ISSUE TITLE
Running python script in docker container

### ISSUE THREAD

**Issue by buckeye17** [rapidsai/docker#305]
I'm attempting to run a python web app which has several dask & CUDA related libraries inside a rapids docker container.  Here's my docker command:
```
docker run --rm -it -e EXTRA_CONDA_PACKAGES="dash dash-bootstrap-components dash-table dask dask_cudf datashader geopandas matplotlib pandas visdcc xarray" -e EXTRA_PIP_PACKAGES="dash-daq geographiclib geopy openrouteservice progress" -v $(pwd):/rapids/app -p 127.0.0.1:8051:8051 rapidsai/rapidsai:cuda11.0-base-ubuntu20.04-py3.8
```
Once the command runs and I get terminal access to the container, I run my python web app and get the following error message:
```
Traceback (most recent call last):
  File "app/app.py", line 58, in <module>
    import dask_cudf as dd
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cudf/__init__.py", line 3, in <module>
    import cudf
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 18, in validate_setup
    from rmm._cuda.gpu import (
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/rmm/mr.py", line 2, in <module>
    from rmm._lib.memory_resource import (
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 3, in <module>
    from .device_buffer import DeviceBuffer
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```
If I modify the `docker run` command shown above by adding the `--gpus all` flag, the docker container fails to start, with the following error message:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown.
```
Any ideas on how I can fix this problem?

I'll note that by using conda directly on the host machine, I'm able to run this web app without any problems.

**Comment by ajschmidt8** [comment]
Hi @buckeye17,

The second error message that you posted:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown.
```

could indicate an issue with the NVIDIA drivers installed on your machine. Can you run the following command on the host machine and post the output here?

```sh
nvidia-smi
```

**Comment by buckeye17** [comment]
@ajschmidt8 Thanks for your help!  When I tried running `nvidia-smi` the command also failed to run, which was new development (I had run it dozens of times earlier in the week).  I asked an admin to take a look and he simply reset the machine.  Mysteriously, this seems to have fixed all of my problems.  Since my issue has been resolved, I've closed the the issue.
